import type { WorkingSchedule } from "../../Entities/WorkingSchedualeData";

export const dummySchedule: WorkingSchedule[] = [

    {
        id: 1,
        date: "2026-06-28",
        day: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 2,
        date: "2026-06-29",
        day: "Monday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 3,
        date: "2026-06-30",
        day: "Tuesday",
        startTime: "08:00",
        endTime: "14:00",
        isAvailable: true,
    },
    {
        id: 4,
        date: "2026-07-01",
        day: "Wednesday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
    },
    {
        id: 5,
        date: "2026-07-02",
        day: "Thursday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
    },
    {
        id: 6,
        date: "2026-07-03",
        day: "Friday",
        startTime: "",
        endTime: "",
        isAvailable: false, 
    },
    {
        id: 7,
        date: "2026-07-04",
        day: "Saturday",
        startTime: "",
        endTime: "",
        isAvailable: false,     },

    
    {
        id: 8,
        date: "2026-07-05",
        day: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 9,
        date: "2026-07-06",
        day: "Monday",
        startTime: "07:00",
        endTime: "15:00",
        isAvailable: true,
    },
    {
        id: 10,
        date: "2026-07-07",
        day: "Tuesday",
        startTime: "10:00",
        endTime: "18:00",
        isAvailable: true,
    },

    
    {
        id: 11,
        date: "2026-07-10",
        day: "Friday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },
    {
        id: 12,
        date: "2026-07-11",
        day: "Saturday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },

    
    {
        id: 13,
        date: "2026-07-12",
        day: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 14,
        date: "2026-07-13",
        day: "Monday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 15,
        date: "2026-07-14",
        day: "Tuesday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 16,
        date: "2026-07-15",
        day: "Wednesday",
        startTime: "08:00",
        endTime: "12:00", 
        isAvailable: true,
    },
    {
        id: 17,
        date: "2026-07-16",
        day: "Thursday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
    },
    {
        id: 18,
        date: "2026-07-17",
        day: "Friday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },
    {
        id: 19,
        date: "2026-07-18",
        day: "Saturday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },

   
    {
        id: 20,
        date: "2026-07-19",
        day: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 21,
        date: "2026-07-20",
        day: "Monday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 22,
        date: "2026-07-21",
        day: "Tuesday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },

   
    {
        id: 23,
        date: "2026-07-23",
        day: "Thursday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
    },
    {
        id: 24,
        date: "2026-07-24",
        day: "Friday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },
    {
        id: 25,
        date: "2026-07-25",
        day: "Saturday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },

    
    {
        id: 26,
        date: "2026-07-26",
        day: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 27,
        date: "2026-07-27",
        day: "Monday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 28,
        date: "2026-07-28",
        day: "Tuesday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 29,
        date: "2026-07-29",
        day: "Wednesday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 30,
        date: "2026-07-30",
        day: "Thursday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },
    {
        id: 31,
        date: "2026-07-31",
        day: "Friday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },

    
    {
        id: 32,
        date: "2026-08-01",
        day: "Saturday",
        startTime: "",
        endTime: "",
        isAvailable: false,
    },
    {
        id: 33,
        date: "2026-08-02",
        day: "Sunday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
    },

];